[workspace]
members = [ 'utils', 'day_01', 'day_02' ]

[workspace.dependencies]
anyhow = "1.0.66"
tracing = "0.1"
tracing-subscriber = "0.3.16"
ansi_term = "0.12.1"
thiserror = "1.0.37"
im = "15.1.0"
regex = "1.7.0"
lazy_static = "1.4.0"
itertools = "0.10.5"