[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
ansi_term = { workspace = true }
thiserror = { workspace = true }
itertools = { workspace = true }
im = { workspace = true }
num = "0.4.0"